apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: discord-ui-showcase-ghcr-pull
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: discord-ui-showcase
  mount: kv
  type: kv-v2
  path: apps/discord-ui-showcase/prod/image-pull
  refreshAfter: 30s
  destination:
    name: discord-ui-showcase-ghcr-pull
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludes:
        - ".*"
      templates:
        .dockerconfigjson:
          text: |
            {"auths":{"{{ .Secrets.server }}":{"username":"{{ .Secrets.username }}","password":"{{ .Secrets.password }}","auth":"{{ .Secrets.auth }}"}}}
