apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: draft-review-ghcr-pull
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: draft-review
  mount: kv
  type: kv-v2
  path: apps/draft-review/prod/image-pull
  refreshAfter: 30s
  destination:
    name: draft-review-ghcr-pull
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludes:
        - ".*"
      templates:
        .dockerconfigjson:
          text: |
            {"auths":{"{{ .Secrets.server }}":{"username":"{{ .Secrets.username }}","password":"{{ .Secrets.password }}","auth":"{{ .Secrets.auth }}"}}}
