apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: draft-review
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - db-bootstrap-serviceaccount.yaml
  - vault-connection.yaml
  - vault-auth.yaml
  - db-bootstrap-vault-auth.yaml
  - runtime-secret.yaml
  - image-pull-secret.yaml
  - postgres-admin-secret.yaml
  - db-bootstrap-script-configmap.yaml
  - db-bootstrap-job.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
