apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: draft-review-media
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
