apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: draft-review-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: draft-review
  mount: kv
  type: kv-v2
  path: apps/draft-review/prod/runtime
  refreshAfter: 30s
  destination:
    name: draft-review-runtime
    create: true
    overwrite: true
