apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: draft-review
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: draft-review
    serviceAccount: draft-review
