apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  address: https://vault.yolo.scapegoat.dev
  skipTLSVerify: false
