apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mysql-auth
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: mysql
  mount: kv
  type: kv-v2
  path: infra/mysql/cluster
  refreshAfter: 30s
  destination:
    name: mysql-auth
    create: true
    overwrite: true
