apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coinvault

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - persistentvolumeclaim.yaml
  - vault-connection.yaml
  - vault-auth.yaml
  - vault-static-secret-runtime.yaml
  - vault-static-secret-pinocchio.yaml
  - vault-static-secret-image-pull.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - mysql-ide-deployment.yaml
  - mysql-ide-service.yaml
  - mysql-ide-ingress.yaml
