apiVersion: v1
kind: Service
metadata:
  name: coinvault
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: coinvault
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: coinvault
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: http
