apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coinvault-ghcr-pull
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: coinvault
  mount: kv
  type: kv-v2
  path: apps/coinvault/prod/image-pull
  refreshAfter: 30s
  destination:
    name: coinvault-ghcr-pull
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludes:
        - ".*"
      templates:
        .dockerconfigjson:
          text: |
            {"auths":{"{{ .Secrets.server }}":{"username":"{{ .Secrets.username }}","password":"{{ .Secrets.password }}","auth":"{{ .Secrets.auth }}"}}}
