apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coinvault-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: coinvault
  mount: kv
  type: kv-v2
  path: apps/coinvault/prod/runtime
  refreshAfter: 30s
  destination:
    name: coinvault-runtime
    create: true
    overwrite: true
