apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: coinvault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: coinvault-prod
    serviceAccount: coinvault
