apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: primary
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: primary
