apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-auth
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: postgres
  mount: kv
  type: kv-v2
  path: infra/postgres/cluster
  refreshAfter: 30s
  destination:
    name: postgres-auth
    create: true
    overwrite: true
