apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 84.0.0
    helm:
      releaseName: monitoring
      valuesObject:
        fullnameOverride: monitoring

        grafana:
          enabled: true
          ingress:
            enabled: false
          initChownData:
            enabled: true
            securityContext:
              capabilities:
                add:
                  - CHOWN
                  - DAC_OVERRIDE
                  - FOWNER
                drop:
                  - ALL
              readOnlyRootFilesystem: false
              runAsNonRoot: false
              runAsUser: 0
              seccompProfile:
                type: RuntimeDefault
          persistence:
            enabled: true
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            size: 5Gi

        prometheus:
          prometheusSpec:
            retention: 15d
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 20Gi

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 2Gi

        nodeExporter:
          enabled: true

        prometheus-node-exporter:
          hostRootFsMount:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
