namespace: demo
host: demo.example.com

clusterIssuer:
  name: letsencrypt-prod
  email: ops@example.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: letsencrypt-prod-account-key

ingress:
  className: traefik
  tlsSecretName: demo-app-tls
  path: /
  pathType: Prefix
  annotations: {}

argocd:
  enabled: true
  namespace: argocd
  host: argocd.yolo.scapegoat.dev
  tlsSecretName: argocd-server-public-tls
  ingressClassName: traefik
  ingressAnnotations: {}
  server:
    insecure: true

postgres:
  existingSecret: postgres-app
  storageClassName: local-path
  storageSize: 10Gi
  image:
    repository: postgres
    tag: "16-alpine"
  resources: {}

app:
  replicas: 1
  image:
    repository: docker.io/library/demo-go-app
    tag: "1.0.0"
  imagePullPolicy: IfNotPresent
  port: 8080
  resources: {}
