apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-stack
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: demo-stack
    app.kubernetes.io/component: app
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - k3s.scapegoat.dev
      secretName: demo-app-tls
  rules:
    - host: k3s.scapegoat.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-stack-app
                port:
                  number: 80
