apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: keycloak-hair-booking-smtp-sync
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: keycloak-hair-booking-smtp-sync
    serviceAccount: keycloak-hair-booking-smtp-sync
