apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-hair-booking-smtp
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: keycloak-hair-booking-smtp-sync
  mount: kv
  type: kv-v2
  path: apps/hair-booking/prod/ses
  refreshAfter: 30s
  destination:
    name: keycloak-hair-booking-smtp
    create: true
    overwrite: true
