apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  acme:
    email: {{ .Values.clusterIssuer.email | quote }}
    server: {{ .Values.clusterIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingress.className | quote }}
