apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-smoke
spec:
  vaultAuthRef: vso-smoke
  mount: kv
  type: kv-v2
  path: apps/vso-smoke/dev/demo
  refreshAfter: 15s
  destination:
    name: vso-smoke-secret
    create: true
    overwrite: true
