apiVersion: v1
kind: Secret
metadata:
  name: pretext-trace-basic-auth-inline
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: pretext-trace
    app.kubernetes.io/component: web
type: Opaque
stringData:
  users: |
    friend:$2y$05$vQLnGUKeYt/GTIIPPGALIe10WPCgIbI7fq1bLToCG3F1WgGebc8bm
