apiVersion: v1
kind: ServiceAccount
metadata:
  name: pretext-trace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: pretext-trace
imagePullSecrets:
  - name: pretext-trace-ghcr-pull
