apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pretext-trace-basic-auth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: pretext-trace
  mount: kv
  type: kv-v2
  path: apps/pretext-trace/prod/ingress-basic-auth
  refreshAfter: 30s
  hmacSecretData: false
  destination:
    name: pretext-trace-basic-auth
    create: true
    overwrite: true
    transformation:
      excludes:
        - ".*"
      templates:
        users:
          text: |
            {{ .Secrets.users }}
