apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hair-booking-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: hair-booking
  mount: kv
  type: kv-v2
  path: apps/hair-booking/prod/runtime
  refreshAfter: 30s
  destination:
    name: hair-booking-runtime
    create: true
    overwrite: true
