apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus-rule-hetzner-egress.yaml
  - podmonitor-traefik.yaml
  - grafana-dashboard-hetzner-egress.yaml
  - grafana-dashboard-traefik-attribution.yaml
