apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
