apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goja-essay
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: goja-essay
    app.kubernetes.io/component: web
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - goja.yolo.scapegoat.dev
      secretName: goja-essay-tls
  rules:
    - host: goja.yolo.scapegoat.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goja-essay
                port:
                  number: 80
