apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: backup-storage
  namespace: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: redis
  mount: kv
  type: kv-v2
  path: infra/backups/object-storage
  refreshAfter: 30s
  destination:
    name: backup-storage
    create: true
    overwrite: true
