apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-auth
  namespace: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: redis
  mount: kv
  type: kv-v2
  path: infra/redis/cluster
  refreshAfter: 30s
  destination:
    name: redis-auth
    create: true
    overwrite: true
